plugins:
  - checksum: add22d627ca8aafa931e7715c5b8f61c6438909a3a779ba11bab7395476365b65bd4cafd30c92fd88d8b2dbbe6b4e952f864aec165aa499a0087941f1ae057db
    path: .yarn/plugins/@yarnpkg/plugin-yarnpnp2nix.cjs
    spec: "https://github.com/madjam002/yarnpnp2nix/raw/master/plugin/dist/plugin-yarnpnp2nix.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.29.cjs
