# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  settings = {
    compressionLevel = "mixed";
  };
  packages = {
    "@babel/runtime@npm:7.20.6" = {
      name = "@babel/runtime";
      reference = "npm:7.20.6";
      linkType = "HARD";
      outputName = "babel-runtime-7.20.6-ef7cda3b78";
      outputHash = "78950a4a005ede7d262fd678764fe0aaa202d517a5f024800dcbcf15065a7dee6f628de764c1f6ccefc82efa4d6bb17ff9b1eb13c00d8b7f618cea08a45816fa";
      flatName = "runtime";
      languageName = "node";
      scope = "babel";
      descriptorRange = "npm:^7.6.3";
      checksum = "9/78950a4a005ede7d262fd678764fe0aaa202d517a5f024800dcbcf15065a7dee6f628de764c1f6ccefc82efa4d6bb17ff9b1eb13c00d8b7f618cea08a45816fa";
      dependencies = {
        "regenerator-runtime" = packages."regenerator-runtime@npm:0.13.11";
      };
    };
    "@esbuild/android-arm@npm:0.16.3" = {
      name = "@esbuild/android-arm";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-android-arm-0.16.3-2062a7b223";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch32);
      flatName = "android-arm";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/android-arm64@npm:0.16.3" = {
      name = "@esbuild/android-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-android-arm64-0.16.3-330ae0b5ab";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "android-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/android-x64@npm:0.16.3" = {
      name = "@esbuild/android-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-android-x64-0.16.3-d4bb1e0ee9";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "android-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/darwin-arm64@npm:0.16.3" = {
      name = "@esbuild/darwin-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-darwin-arm64-0.16.3-e4da2a32cb";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isDarwin) && (stdenv.isAarch64);
      flatName = "darwin-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/darwin-x64@npm:0.16.3" = {
      name = "@esbuild/darwin-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-darwin-x64-0.16.3-34c182c399";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isDarwin) && (stdenv.isx86_64);
      flatName = "darwin-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/freebsd-arm64@npm:0.16.3" = {
      name = "@esbuild/freebsd-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-freebsd-arm64-0.16.3-17547525a3";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "freebsd-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/freebsd-x64@npm:0.16.3" = {
      name = "@esbuild/freebsd-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-freebsd-x64-0.16.3-2065caac93";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "freebsd-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-arm@npm:0.16.3" = {
      name = "@esbuild/linux-arm";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-arm-0.16.3-d552c367b0";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isAarch32);
      flatName = "linux-arm";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-arm64@npm:0.16.3" = {
      name = "@esbuild/linux-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-arm64-0.16.3-7fe1a8fcf0";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isAarch64);
      flatName = "linux-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-ia32@npm:0.16.3" = {
      name = "@esbuild/linux-ia32";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-ia32-0.16.3-571d0979d3";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isi686);
      flatName = "linux-ia32";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-loong64@npm:0.16.3" = {
      name = "@esbuild/linux-loong64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-loong64-0.16.3-902a0fff9d";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-loong64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-mips64el@npm:0.16.3" = {
      name = "@esbuild/linux-mips64el";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-mips64el-0.16.3-681cc7561e";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-mips64el";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-ppc64@npm:0.16.3" = {
      name = "@esbuild/linux-ppc64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-ppc64-0.16.3-f9eec20cfb";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-ppc64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-riscv64@npm:0.16.3" = {
      name = "@esbuild/linux-riscv64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-riscv64-0.16.3-452a40ba2b";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-riscv64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-s390x@npm:0.16.3" = {
      name = "@esbuild/linux-s390x";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-s390x-0.16.3-62c5211c73";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-s390x";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-x64@npm:0.16.3" = {
      name = "@esbuild/linux-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-x64-0.16.3-7732358ecf";
      outputHashByPlatform = {
        "x86_64-linux" = "sha512-GHN+d30VvIYAWoW+Xg4I5f/b0NuzEicIUY4eWgCNrQnKg1w0UxMbIEw3MHnAZo9ZyEacfSk6Re8g6kQqVQRNnQ==";
      };
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isx86_64);
      flatName = "linux-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/netbsd-x64@npm:0.16.3" = {
      name = "@esbuild/netbsd-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-netbsd-x64-0.16.3-8b6dadf7f3";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "netbsd-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/openbsd-x64@npm:0.16.3" = {
      name = "@esbuild/openbsd-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-openbsd-x64-0.16.3-263702d54c";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "openbsd-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/sunos-x64@npm:0.16.3" = {
      name = "@esbuild/sunos-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-sunos-x64-0.16.3-5742211241";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "sunos-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/win32-arm64@npm:0.16.3" = {
      name = "@esbuild/win32-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-win32-arm64-0.16.3-ab2a4b8c03";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "win32-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/win32-ia32@npm:0.16.3" = {
      name = "@esbuild/win32-ia32";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-win32-ia32-0.16.3-4f8c85aebb";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isi686);
      flatName = "win32-ia32";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/win32-x64@npm:0.16.3" = {
      name = "@esbuild/win32-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-win32-x64-0.16.3-92b8a6bfb7";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "win32-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@redux-saga/core@npm:1.2.1" = {
      name = "@redux-saga/core";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-core-1.2.1-26e66f51bb";
      outputHash = "6da1c29ce88c75df4df9f39cc08d6d715b625e098662693e40e907407bf30fedb5a83fb502a2315df705b417f79f1be7000c56bec057bc65c89f0159510a49e2";
      flatName = "core";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "9/6da1c29ce88c75df4df9f39cc08d6d715b625e098662693e40e907407bf30fedb5a83fb502a2315df705b417f79f1be7000c56bec057bc65c89f0159510a49e2";
      dependencies = {
        "@babel/runtime" = packages."@babel/runtime@npm:7.20.6";
        "@redux-saga/deferred" = packages."@redux-saga/deferred@npm:1.2.1";
        "@redux-saga/delay-p" = packages."@redux-saga/delay-p@npm:1.2.1";
        "@redux-saga/is" = packages."@redux-saga/is@npm:1.1.3";
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
        "@redux-saga/types" = packages."@redux-saga/types@npm:1.2.1";
        "redux" = packages."redux@npm:4.2.0";
        "typescript-tuple" = packages."typescript-tuple@npm:2.2.1";
      };
    };
    "@redux-saga/deferred@npm:1.2.1" = {
      name = "@redux-saga/deferred";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-deferred-1.2.1-ec57ca1b3b";
      outputHash = "efc2e19f5e551169d01572bac5089b76d14c939e8ccf9e4dfe6130092b72e9ac2e5b9691d03dc1fddd07fda14e0129f8a6cac3d09176aa90b928a7d35e69ab31";
      flatName = "deferred";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "9/efc2e19f5e551169d01572bac5089b76d14c939e8ccf9e4dfe6130092b72e9ac2e5b9691d03dc1fddd07fda14e0129f8a6cac3d09176aa90b928a7d35e69ab31";
    };
    "@redux-saga/delay-p@npm:1.2.1" = {
      name = "@redux-saga/delay-p";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-delay-p-1.2.1-aed55ef6d3";
      outputHash = "f68e0f21869699414198941defeaca821bb7a7a6b3704a69013eba270780d410e095f3344723dbc4f27acbb6175b4a9f984f342508a5a02f3b81819b5e3592af";
      flatName = "delay-p";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "9/f68e0f21869699414198941defeaca821bb7a7a6b3704a69013eba270780d410e095f3344723dbc4f27acbb6175b4a9f984f342508a5a02f3b81819b5e3592af";
      dependencies = {
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
      };
    };
    "@redux-saga/is@npm:1.1.3" = {
      name = "@redux-saga/is";
      reference = "npm:1.1.3";
      linkType = "HARD";
      outputName = "redux-saga-is-1.1.3-b810d8c710";
      outputHash = "99f6de35e4ab7acac3dc9117370634099e84a2c03fa1e2bb45838594f38b405294065ef53a8598ce64b67d72e3656d52ec204baa68b84b469d69e36a21e7ac36";
      flatName = "is";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.1.3";
      checksum = "9/99f6de35e4ab7acac3dc9117370634099e84a2c03fa1e2bb45838594f38b405294065ef53a8598ce64b67d72e3656d52ec204baa68b84b469d69e36a21e7ac36";
      dependencies = {
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
        "@redux-saga/types" = packages."@redux-saga/types@npm:1.2.1";
      };
    };
    "@redux-saga/symbols@npm:1.1.3" = {
      name = "@redux-saga/symbols";
      reference = "npm:1.1.3";
      linkType = "HARD";
      outputName = "redux-saga-symbols-1.1.3-d95f758fa4";
      outputHash = "716a9a8be363ce9ac6b1825a2c0fb8d7576771bedb3f9357c34c441e7604ecd2a14a28a267225035e00953125f28b261067a3f0e3f27721df1d86e48da936c19";
      flatName = "symbols";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.1.3";
      checksum = "9/716a9a8be363ce9ac6b1825a2c0fb8d7576771bedb3f9357c34c441e7604ecd2a14a28a267225035e00953125f28b261067a3f0e3f27721df1d86e48da936c19";
    };
    "@redux-saga/types@npm:1.2.1" = {
      name = "@redux-saga/types";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-types-1.2.1-e3cea8c4d4";
      outputHash = "d45f477e7ef9c319e8fb955f0d09cc386edee184447eef3c566047b7867c491291799fe95271d2bc1dd41d224ee6be25c31bc7708d9ffd4f4d4ba1c9df6208e2";
      flatName = "types";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "9/d45f477e7ef9c319e8fb955f0d09cc386edee184447eef3c566047b7867c491291799fe95271d2bc1dd41d224ee6be25c31bc7708d9ffd4f4d4ba1c9df6208e2";
    };
    "@types/node@npm:18.11.12" = {
      name = "@types/node";
      reference = "npm:18.11.12";
      linkType = "HARD";
      outputName = "types-node-18.11.12-3e4f66dc1e";
      outputHash = "4b12f985ea2509f389f5d318677939b9d59bb3e03977512ac3e73aaa390c5a9524d1d762d215a6efbc457e7d70697b3dd25f50fe8ad6a0fa3490828a41b2bc9c";
      flatName = "node";
      languageName = "node";
      scope = "types";
      descriptorRange = "npm:^18.11.12";
      checksum = "9/4b12f985ea2509f389f5d318677939b9d59bb3e03977512ac3e73aaa390c5a9524d1d762d215a6efbc457e7d70697b3dd25f50fe8ad6a0fa3490828a41b2bc9c";
    };
    "debug@npm:4.3.4" = {
      name = "debug";
      reference = "npm:4.3.4";
      linkType = "HARD";
      outputName = "debug-4.3.4-4513954577";
      outputHash = "ab50d98b6f2a0e803379e8f789017f4215efd0e085774623e462c691e9f99bfd359a35f7424ff401da3ea58b31f89ceebc9ea35779b4a94f78b0ee3e235b6640";
      flatName = "debug";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.3.4";
      checksum = "9/ab50d98b6f2a0e803379e8f789017f4215efd0e085774623e462c691e9f99bfd359a35f7424ff401da3ea58b31f89ceebc9ea35779b4a94f78b0ee3e235b6640";
      dependencies = {
        "ms" = packages."ms@npm:2.1.2";
      };
      packagePeers = [
        "@types/supports-color"
        "supports-color"
      ];
    };
    "debug@virtual:be403fd6f7b6e95bd4aec31d1bf9c334857c71f759221be0219c12459d446557184251418833011b9a89f7d1cde9505518db3fa18f3c4021e9d387d9702dbff4#npm:4.3.4" = {
      name = "debug";
      reference = "virtual:be403fd6f7b6e95bd4aec31d1bf9c334857c71f759221be0219c12459d446557184251418833011b9a89f7d1cde9505518db3fa18f3c4021e9d387d9702dbff4#npm:4.3.4";
      canonicalPackage = packages."debug@npm:4.3.4";
      dependencies = {
        "ms" = packages."ms@npm:2.1.2";
      };
    };
    "esbuild-register@npm:3.4.1" = {
      name = "esbuild-register";
      reference = "npm:3.4.1";
      linkType = "HARD";
      outputName = "esbuild-register-3.4.1-2c0fbc0674";
      outputHash = "0d2e5620146b408df4f9f82e11e74463dd8d8e81a0e617422e0ebe891d2eb6a857419cc7013e990cd89cce3b0258c2e9cb8be8ca85250838b6d191b4c9f827f1";
      flatName = "esbuild-register";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.4.1";
      checksum = "9/0d2e5620146b408df4f9f82e11e74463dd8d8e81a0e617422e0ebe891d2eb6a857419cc7013e990cd89cce3b0258c2e9cb8be8ca85250838b6d191b4c9f827f1";
      dependencies = {
        "debug" = packages."debug@npm:4.3.4";
      };
      packagePeers = [
        "@types/esbuild"
        "esbuild"
      ];
    };
    "esbuild-register@virtual:55066ab27bd0662ac7a3999c80cf073281b6efcfe8250391af8ff681f2a227cf5b0b640e0c04304c19717e5107485d72c20d5b9bd2bab8ac0bfa8b0b73ea896b#npm:3.4.1" = {
      name = "esbuild-register";
      reference = "virtual:55066ab27bd0662ac7a3999c80cf073281b6efcfe8250391af8ff681f2a227cf5b0b640e0c04304c19717e5107485d72c20d5b9bd2bab8ac0bfa8b0b73ea896b#npm:3.4.1";
      canonicalPackage = packages."esbuild-register@npm:3.4.1";
      dependencies = {
        "esbuild" = packages."esbuild@npm:0.16.3";
        "debug" = packages."debug@virtual:be403fd6f7b6e95bd4aec31d1bf9c334857c71f759221be0219c12459d446557184251418833011b9a89f7d1cde9505518db3fa18f3c4021e9d387d9702dbff4#npm:4.3.4";
      };
    };
    "esbuild@npm:0.16.3" = {
      name = "esbuild";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-0.16.3-4dec320b34";
      outputHashByPlatform = {
        "x86_64-linux" = "sha512-8UxyetHT29Ml7DXfQTATezQXwR0YRZ7iRViVPi7o4UgAMiXBJyLd3GOhCaANl/LzzzqhFNTpsJNfp0ldV09l6A==";
      };
      shouldBeUnplugged = true;
      flatName = "esbuild";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.16.3";
      checksum = "9/b5a256034ff6c1ddefcfa90555ae938c550a1cf0a984dee0a8fa5fa81ce76054b4493703a02fb750711e0c5af2a2a3f393c52f7e2dc505083d9d41982bea1af8";
      bin = {
        "esbuild" = "bin/esbuild";
      };
      dependencies = {
        "@esbuild/android-arm64" = packages."@esbuild/android-arm64@npm:0.16.3";
        "@esbuild/android-arm" = packages."@esbuild/android-arm@npm:0.16.3";
        "@esbuild/android-x64" = packages."@esbuild/android-x64@npm:0.16.3";
        "@esbuild/darwin-arm64" = packages."@esbuild/darwin-arm64@npm:0.16.3";
        "@esbuild/darwin-x64" = packages."@esbuild/darwin-x64@npm:0.16.3";
        "@esbuild/freebsd-arm64" = packages."@esbuild/freebsd-arm64@npm:0.16.3";
        "@esbuild/freebsd-x64" = packages."@esbuild/freebsd-x64@npm:0.16.3";
        "@esbuild/linux-arm64" = packages."@esbuild/linux-arm64@npm:0.16.3";
        "@esbuild/linux-arm" = packages."@esbuild/linux-arm@npm:0.16.3";
        "@esbuild/linux-ia32" = packages."@esbuild/linux-ia32@npm:0.16.3";
        "@esbuild/linux-loong64" = packages."@esbuild/linux-loong64@npm:0.16.3";
        "@esbuild/linux-mips64el" = packages."@esbuild/linux-mips64el@npm:0.16.3";
        "@esbuild/linux-ppc64" = packages."@esbuild/linux-ppc64@npm:0.16.3";
        "@esbuild/linux-riscv64" = packages."@esbuild/linux-riscv64@npm:0.16.3";
        "@esbuild/linux-s390x" = packages."@esbuild/linux-s390x@npm:0.16.3";
        "@esbuild/linux-x64" = packages."@esbuild/linux-x64@npm:0.16.3";
        "@esbuild/netbsd-x64" = packages."@esbuild/netbsd-x64@npm:0.16.3";
        "@esbuild/openbsd-x64" = packages."@esbuild/openbsd-x64@npm:0.16.3";
        "@esbuild/sunos-x64" = packages."@esbuild/sunos-x64@npm:0.16.3";
        "@esbuild/win32-arm64" = packages."@esbuild/win32-arm64@npm:0.16.3";
        "@esbuild/win32-ia32" = packages."@esbuild/win32-ia32@npm:0.16.3";
        "@esbuild/win32-x64" = packages."@esbuild/win32-x64@npm:0.16.3";
      };
    };
    "ip-matching@npm:2.1.2" = {
      name = "ip-matching";
      reference = "npm:2.1.2";
      linkType = "HARD";
      outputName = "ip-matching-2.1.2-60bdd3d654";
      outputHash = "1a9e1741a3614fada2fb2df119359e98777748f8a214dac062c4e6d5b64a51dbb4b34300d9a21123a23051fff0a9c2e94166974bbc49cbb638ad117dc49ee82e";
      flatName = "ip-matching";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.1.2";
      checksum = "9/1a9e1741a3614fada2fb2df119359e98777748f8a214dac062c4e6d5b64a51dbb4b34300d9a21123a23051fff0a9c2e94166974bbc49cbb638ad117dc49ee82e";
    };
    "ms@npm:2.1.2" = {
      name = "ms";
      reference = "npm:2.1.2";
      linkType = "HARD";
      outputName = "ms-2.1.2-ec0c1512ff";
      outputHash = "3f46af60a08158f1c77746c06c2f6c7aba7feddafd41335f9baa2d7e0741d7539774aa7d5d1661a7f2b7eed55a7063771297eea016051924dbb04d4c2bf40bcb";
      flatName = "ms";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.1.2";
      checksum = "9/3f46af60a08158f1c77746c06c2f6c7aba7feddafd41335f9baa2d7e0741d7539774aa7d5d1661a7f2b7eed55a7063771297eea016051924dbb04d4c2bf40bcb";
    };
    "redux-saga@npm:1.2.1" = {
      name = "redux-saga";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-1.2.1-4875573c97";
      outputHash = "a4e4f0d6df19738f494ca12814d0fc510a26ff25c1f1a810450dc3bbb89a3903870c941f08f465ce1ea2015e2e271e91d923c8e0932f066be9154d95f052ba83";
      flatName = "redux-saga";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.2.1";
      checksum = "9/a4e4f0d6df19738f494ca12814d0fc510a26ff25c1f1a810450dc3bbb89a3903870c941f08f465ce1ea2015e2e271e91d923c8e0932f066be9154d95f052ba83";
      dependencies = {
        "@redux-saga/core" = packages."@redux-saga/core@npm:1.2.1";
      };
    };
    "redux@npm:4.2.0" = {
      name = "redux";
      reference = "npm:4.2.0";
      linkType = "HARD";
      outputName = "redux-4.2.0-4688cc8d65";
      outputHash = "9239ab43da6a18375b413e128e9b808f28d46cbadfc58a371921396f82efd0187f17e6cd86c01080975c1778304b93a1546d735411067c54b1d81bd9e2e46307";
      flatName = "redux";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.4";
      checksum = "9/9239ab43da6a18375b413e128e9b808f28d46cbadfc58a371921396f82efd0187f17e6cd86c01080975c1778304b93a1546d735411067c54b1d81bd9e2e46307";
      dependencies = {
        "@babel/runtime" = packages."@babel/runtime@npm:7.20.6";
      };
    };
    "regenerator-runtime@npm:0.13.11" = {
      name = "regenerator-runtime";
      reference = "npm:0.13.11";
      linkType = "HARD";
      outputName = "regenerator-runtime-0.13.11-90bf536060";
      outputHash = "0485db63ce47760e28329590cb9f8b208365d076dbf2edaa32e551a7c0451fc6f7557b225268422c960ffa4fbc6ff86d63d6a747aacbf6b10ed6a747b432e3c8";
      flatName = "regenerator-runtime";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.13.11";
      checksum = "9/0485db63ce47760e28329590cb9f8b208365d076dbf2edaa32e551a7c0451fc6f7557b225268422c960ffa4fbc6ff86d63d6a747aacbf6b10ed6a747b432e3c8";
    };
    "stream-chain@npm:2.2.5" = {
      name = "stream-chain";
      reference = "npm:2.2.5";
      linkType = "HARD";
      outputName = "stream-chain-2.2.5-ad363478fb";
      outputHash = "8781cec2d1786e566197b0e1126dd4ae8a669f0e658b09d7e2b69b91aeffbe6f88fdf5d5ed36a12fda4f7220f19a941fc23d5a6fef196238ae5a3ad1493ca3ce";
      flatName = "stream-chain";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.2.5";
      checksum = "9/8781cec2d1786e566197b0e1126dd4ae8a669f0e658b09d7e2b69b91aeffbe6f88fdf5d5ed36a12fda4f7220f19a941fc23d5a6fef196238ae5a3ad1493ca3ce";
    };
    "stream-json@npm:1.7.5" = {
      name = "stream-json";
      reference = "npm:1.7.5";
      linkType = "HARD";
      outputName = "stream-json-1.7.5-47509e8de8";
      outputHash = "b4146aeb3c56b24fcbaa63324ba4e58f4ad3047a099d3d81ec5f9696bab454e9e327278481de654750bdb37368e909fe20b98ea38a3f21288769d99b2ca7f755";
      flatName = "stream-json";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.7.5";
      checksum = "9/b4146aeb3c56b24fcbaa63324ba4e58f4ad3047a099d3d81ec5f9696bab454e9e327278481de654750bdb37368e909fe20b98ea38a3f21288769d99b2ca7f755";
      dependencies = {
        "stream-chain" = packages."stream-chain@npm:2.2.5";
      };
    };
    "tailscale-prometheus-sd@workspace:." = {
      name = "tailscale-prometheus-sd";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "tailscale-prometheus-sd-0.0.0-55066ab27b";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "tailscale-prometheus-sd";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
      bin = {
        "tailscale-prometheus-sd" = "tailscale-prometheus-sd.js";
      };
      dependencies = {
        "@types/node" = packages."@types/node@npm:18.11.12";
        "ip-matching" = packages."ip-matching@npm:2.1.2";
        "redux-saga" = packages."redux-saga@npm:1.2.1";
        "stream-chain" = packages."stream-chain@npm:2.2.5";
        "stream-json" = packages."stream-json@npm:1.7.5";
      };
      devDependencies = {
        "esbuild" = packages."esbuild@npm:0.16.3";
        "esbuild-register" = packages."esbuild-register@virtual:55066ab27bd0662ac7a3999c80cf073281b6efcfe8250391af8ff681f2a227cf5b0b640e0c04304c19717e5107485d72c20d5b9bd2bab8ac0bfa8b0b73ea896b#npm:3.4.1";
        "typescript" = packages."typescript@patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=7f4d21";
      };
    };
    "typescript-compare@npm:0.0.2" = {
      name = "typescript-compare";
      reference = "npm:0.0.2";
      linkType = "HARD";
      outputName = "typescript-compare-0.0.2-86f99ed6e8";
      outputHash = "c9945b8084819b9bb7aa6a370d570cdc47b7498dc3f1aba16376d4d6f05c3ad7324c5f54903534f30986cfdec90775f281f6769f399aa9d77bcf54300f40cb92";
      flatName = "typescript-compare";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.0.2";
      checksum = "9/c9945b8084819b9bb7aa6a370d570cdc47b7498dc3f1aba16376d4d6f05c3ad7324c5f54903534f30986cfdec90775f281f6769f399aa9d77bcf54300f40cb92";
      dependencies = {
        "typescript-logic" = packages."typescript-logic@npm:0.0.0";
      };
    };
    "typescript-logic@npm:0.0.0" = {
      name = "typescript-logic";
      reference = "npm:0.0.0";
      linkType = "HARD";
      outputName = "typescript-logic-0.0.0-f343262bb5";
      outputHash = "3b2ed9aeb4a0abc7c422b46d0c09edae5053ddb0723e359b9e2f709655c5c42256cf9db0b390706f4066daaf46252900c95fd21f0b19a97d3e06e311addba219";
      flatName = "typescript-logic";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.0.0";
      checksum = "9/3b2ed9aeb4a0abc7c422b46d0c09edae5053ddb0723e359b9e2f709655c5c42256cf9db0b390706f4066daaf46252900c95fd21f0b19a97d3e06e311addba219";
    };
    "typescript-tuple@npm:2.2.1" = {
      name = "typescript-tuple";
      reference = "npm:2.2.1";
      linkType = "HARD";
      outputName = "typescript-tuple-2.2.1-b78fa3093a";
      outputHash = "53f3b380618ef56eb7c58f5cf027baf547416d8ef8145ac0b053e4f61bbef581c0f018393868e4cfa02c281d2250a9b8fd21d12615db992033e100702f4dea61";
      flatName = "typescript-tuple";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.2.1";
      checksum = "9/53f3b380618ef56eb7c58f5cf027baf547416d8ef8145ac0b053e4f61bbef581c0f018393868e4cfa02c281d2250a9b8fd21d12615db992033e100702f4dea61";
      dependencies = {
        "typescript-compare" = packages."typescript-compare@npm:0.0.2";
      };
    };
    "typescript@npm:4.9.1-beta" = {
      name = "typescript";
      reference = "npm:4.9.1-beta";
      linkType = "HARD";
      outputName = "typescript-4.9.1-beta-7ff573487c";
      outputHash = "e024fb9fb4abd95c2b2fa877ec9b3aab833a388690709d2e12aef0a9adc12be95fb2f9410b479a5b3c277c240b026e92e82227a5e4ece1868b57ce5be6f45cef";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:4.9.1-beta";
      checksum = "9/e024fb9fb4abd95c2b2fa877ec9b3aab833a388690709d2e12aef0a9adc12be95fb2f9410b479a5b3c277c240b026e92e82227a5e4ece1868b57ce5be6f45cef";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
    "typescript@patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=7f4d21" = {
      name = "typescript";
      reference = "patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=7f4d21";
      linkType = "HARD";
      outputName = "typescript-4.9.1-beta-36a8612e2f";
      outputHash = "54c08d930b680d1c892d5ad9e9fb4ba9d8b2c5e94d6cbbafd22112ba7248c113b0f05a48b07a1b5f6a2f6be904d9ec8ce691fe6cb2fdd864401b6437f0ff36c9";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>";
      checksum = "9/54c08d930b680d1c892d5ad9e9fb4ba9d8b2c5e94d6cbbafd22112ba7248c113b0f05a48b07a1b5f6a2f6be904d9ec8ce691fe6cb2fdd864401b6437f0ff36c9";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
  };
in
{ inherit packages; inherit settings; }
