# This file is generated by running "yarn install" inside your project.
# It is essentially a version of yarn.lock that Nix can better understand
# Manual changes WILL be lost - proceed with caution!
let
  settings = {
    compressionLevel = "mixed";
  };
  packages = {
    "@babel/runtime@npm:7.20.6" = {
      name = "@babel/runtime";
      reference = "npm:7.20.6";
      linkType = "HARD";
      outputName = "babel-runtime-7.20.6-ef7cda3b78";
      outputHash = "c02496762680b616fab4f0c0796c919670e53056e42e1c290fafe7ca42e2fec7d159743e739816a1af8fa65037a384cfa852ec8dc383d3d3c4eea607e6239dd3";
      flatName = "runtime";
      languageName = "node";
      scope = "babel";
      descriptorRange = "npm:^7.6.3";
      checksum = "10/c02496762680b616fab4f0c0796c919670e53056e42e1c290fafe7ca42e2fec7d159743e739816a1af8fa65037a384cfa852ec8dc383d3d3c4eea607e6239dd3";
      dependencies = {
        "regenerator-runtime" = packages."regenerator-runtime@npm:0.13.11";
      };
    };
    "@esbuild/android-arm@npm:0.16.3" = {
      name = "@esbuild/android-arm";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-android-arm-0.16.3-2062a7b223";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch32);
      flatName = "android-arm";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/android-arm64@npm:0.16.3" = {
      name = "@esbuild/android-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-android-arm64-0.16.3-330ae0b5ab";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "android-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/android-x64@npm:0.16.3" = {
      name = "@esbuild/android-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-android-x64-0.16.3-d4bb1e0ee9";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "android-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/darwin-arm64@npm:0.16.3" = {
      name = "@esbuild/darwin-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-darwin-arm64-0.16.3-e4da2a32cb";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isDarwin) && (stdenv.isAarch64);
      flatName = "darwin-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/darwin-x64@npm:0.16.3" = {
      name = "@esbuild/darwin-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-darwin-x64-0.16.3-34c182c399";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isDarwin) && (stdenv.isx86_64);
      flatName = "darwin-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/freebsd-arm64@npm:0.16.3" = {
      name = "@esbuild/freebsd-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-freebsd-arm64-0.16.3-17547525a3";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "freebsd-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/freebsd-x64@npm:0.16.3" = {
      name = "@esbuild/freebsd-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-freebsd-x64-0.16.3-2065caac93";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "freebsd-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-arm@npm:0.16.3" = {
      name = "@esbuild/linux-arm";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-arm-0.16.3-d552c367b0";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isAarch32);
      flatName = "linux-arm";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-arm64@npm:0.16.3" = {
      name = "@esbuild/linux-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-arm64-0.16.3-7fe1a8fcf0";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isAarch64);
      flatName = "linux-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-ia32@npm:0.16.3" = {
      name = "@esbuild/linux-ia32";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-ia32-0.16.3-571d0979d3";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isi686);
      flatName = "linux-ia32";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-loong64@npm:0.16.3" = {
      name = "@esbuild/linux-loong64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-loong64-0.16.3-902a0fff9d";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-loong64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-mips64el@npm:0.16.3" = {
      name = "@esbuild/linux-mips64el";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-mips64el-0.16.3-681cc7561e";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-mips64el";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-ppc64@npm:0.16.3" = {
      name = "@esbuild/linux-ppc64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-ppc64-0.16.3-f9eec20cfb";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-ppc64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-riscv64@npm:0.16.3" = {
      name = "@esbuild/linux-riscv64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-riscv64-0.16.3-452a40ba2b";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-riscv64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-s390x@npm:0.16.3" = {
      name = "@esbuild/linux-s390x";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-s390x-0.16.3-62c5211c73";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (false);
      flatName = "linux-s390x";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/linux-x64@npm:0.16.3" = {
      name = "@esbuild/linux-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-linux-x64-0.16.3-7732358ecf";
      outputHashByPlatform = {
        "x86_64-linux" = "sha512-GHN+d30VvIYAWoW+Xg4I5f/b0NuzEicIUY4eWgCNrQnKg1w0UxMbIEw3MHnAZo9ZyEacfSk6Re8g6kQqVQRNnQ==";
      };
      shouldBeUnplugged = true;
      installCondition = stdenv: (stdenv.isLinux) && (stdenv.isx86_64);
      flatName = "linux-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/netbsd-x64@npm:0.16.3" = {
      name = "@esbuild/netbsd-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-netbsd-x64-0.16.3-8b6dadf7f3";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "netbsd-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/openbsd-x64@npm:0.16.3" = {
      name = "@esbuild/openbsd-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-openbsd-x64-0.16.3-263702d54c";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "openbsd-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/sunos-x64@npm:0.16.3" = {
      name = "@esbuild/sunos-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-sunos-x64-0.16.3-5742211241";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "sunos-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/win32-arm64@npm:0.16.3" = {
      name = "@esbuild/win32-arm64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-win32-arm64-0.16.3-ab2a4b8c03";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isAarch64);
      flatName = "win32-arm64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/win32-ia32@npm:0.16.3" = {
      name = "@esbuild/win32-ia32";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-win32-ia32-0.16.3-4f8c85aebb";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isi686);
      flatName = "win32-ia32";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@esbuild/win32-x64@npm:0.16.3" = {
      name = "@esbuild/win32-x64";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-win32-x64-0.16.3-92b8a6bfb7";
      outputHash = "";
      shouldBeUnplugged = true;
      installCondition = stdenv: (false) && (stdenv.isx86_64);
      flatName = "win32-x64";
      languageName = "node";
      scope = "esbuild";
      descriptorRange = "npm:0.16.3";
    };
    "@redux-saga/core@npm:1.2.1" = {
      name = "@redux-saga/core";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-core-1.2.1-26e66f51bb";
      outputHash = "e536f69192022e34d206dab7132f8f1f1f97d922653cb6c256e8535b3e9e2a2207ffd0f9f2fb8e9cb2626b299475afcf407de002ee92feb5f9da46a3e33d60c1";
      flatName = "core";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "10/e536f69192022e34d206dab7132f8f1f1f97d922653cb6c256e8535b3e9e2a2207ffd0f9f2fb8e9cb2626b299475afcf407de002ee92feb5f9da46a3e33d60c1";
      dependencies = {
        "@babel/runtime" = packages."@babel/runtime@npm:7.20.6";
        "@redux-saga/deferred" = packages."@redux-saga/deferred@npm:1.2.1";
        "@redux-saga/delay-p" = packages."@redux-saga/delay-p@npm:1.2.1";
        "@redux-saga/is" = packages."@redux-saga/is@npm:1.1.3";
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
        "@redux-saga/types" = packages."@redux-saga/types@npm:1.2.1";
        "redux" = packages."redux@npm:4.2.0";
        "typescript-tuple" = packages."typescript-tuple@npm:2.2.1";
      };
    };
    "@redux-saga/deferred@npm:1.2.1" = {
      name = "@redux-saga/deferred";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-deferred-1.2.1-ec57ca1b3b";
      outputHash = "d06af67b3da8fb9932e5ab6c75de999be113c757f0bc05688e3509ec26c73e823eae6d16626079691342caedc3b179bd2665a006690a9fc372eea80b5bf0d404";
      flatName = "deferred";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "10/d06af67b3da8fb9932e5ab6c75de999be113c757f0bc05688e3509ec26c73e823eae6d16626079691342caedc3b179bd2665a006690a9fc372eea80b5bf0d404";
    };
    "@redux-saga/delay-p@npm:1.2.1" = {
      name = "@redux-saga/delay-p";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-delay-p-1.2.1-aed55ef6d3";
      outputHash = "060533ce8ba6b919caa5d47961eb5d8c1d171519fccd5d44208c26a0b94f3f315c8ea440f1b23af70ed53ebd0445b64567d6a0ac9663a6f703dd8088746ce2b5";
      flatName = "delay-p";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "10/060533ce8ba6b919caa5d47961eb5d8c1d171519fccd5d44208c26a0b94f3f315c8ea440f1b23af70ed53ebd0445b64567d6a0ac9663a6f703dd8088746ce2b5";
      dependencies = {
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
      };
    };
    "@redux-saga/is@npm:1.1.3" = {
      name = "@redux-saga/is";
      reference = "npm:1.1.3";
      linkType = "HARD";
      outputName = "redux-saga-is-1.1.3-b810d8c710";
      outputHash = "36907fcd8bd6acfdcc2e4cca8bb1ae0676e4169375da7dc1ef0dab66b6e367417e1653def98d02ee8e8f654de1f3694d15e5110a614444d3f9f1ad6169476bea";
      flatName = "is";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.1.3";
      checksum = "10/36907fcd8bd6acfdcc2e4cca8bb1ae0676e4169375da7dc1ef0dab66b6e367417e1653def98d02ee8e8f654de1f3694d15e5110a614444d3f9f1ad6169476bea";
      dependencies = {
        "@redux-saga/symbols" = packages."@redux-saga/symbols@npm:1.1.3";
        "@redux-saga/types" = packages."@redux-saga/types@npm:1.2.1";
      };
    };
    "@redux-saga/symbols@npm:1.1.3" = {
      name = "@redux-saga/symbols";
      reference = "npm:1.1.3";
      linkType = "HARD";
      outputName = "redux-saga-symbols-1.1.3-d95f758fa4";
      outputHash = "005cb0939673c0c50b477c40df942e10c31d4f3405561c223640c6f8c2bd29cb207ad089a02ad79a8777f307e128904f00336358aba7e72869f1263fe6744b3e";
      flatName = "symbols";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.1.3";
      checksum = "10/005cb0939673c0c50b477c40df942e10c31d4f3405561c223640c6f8c2bd29cb207ad089a02ad79a8777f307e128904f00336358aba7e72869f1263fe6744b3e";
    };
    "@redux-saga/types@npm:1.2.1" = {
      name = "@redux-saga/types";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-types-1.2.1-e3cea8c4d4";
      outputHash = "521bda9f19cb28c9572bcef28b065908d10b3acec5ad27d0b8993f4d21ecb2ccef8cdbce459e27c60f7cc6a8b87d5d5231048ddb1026527e05d145ea0db5aec2";
      flatName = "types";
      languageName = "node";
      scope = "redux-saga";
      descriptorRange = "npm:^1.2.1";
      checksum = "10/521bda9f19cb28c9572bcef28b065908d10b3acec5ad27d0b8993f4d21ecb2ccef8cdbce459e27c60f7cc6a8b87d5d5231048ddb1026527e05d145ea0db5aec2";
    };
    "@types/node@npm:18.11.12" = {
      name = "@types/node";
      reference = "npm:18.11.12";
      linkType = "HARD";
      outputName = "types-node-18.11.12-3e4f66dc1e";
      outputHash = "b6ec76ea61ef7fdc3c4940ff8437c68f4a902f796f3bdd9845c25f49a6a1f4677049a827b6c660700f095f3ffe9713017e0a2e02e16eb0ff4d070b1da01c8116";
      flatName = "node";
      languageName = "node";
      scope = "types";
      descriptorRange = "npm:^18.11.12";
      checksum = "10/b6ec76ea61ef7fdc3c4940ff8437c68f4a902f796f3bdd9845c25f49a6a1f4677049a827b6c660700f095f3ffe9713017e0a2e02e16eb0ff4d070b1da01c8116";
    };
    "debug@npm:4.3.4" = {
      name = "debug";
      reference = "npm:4.3.4";
      linkType = "HARD";
      outputName = "debug-4.3.4-4513954577";
      outputHash = "0073c3bcbd9cb7d71dd5f6b55be8701af42df3e56e911186dfa46fac3a5b9eb7ce7f377dd1d3be6db8977221f8eb333d945216f645cf56f6b688cd484837d255";
      flatName = "debug";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.3.4";
      checksum = "10/0073c3bcbd9cb7d71dd5f6b55be8701af42df3e56e911186dfa46fac3a5b9eb7ce7f377dd1d3be6db8977221f8eb333d945216f645cf56f6b688cd484837d255";
      dependencies = {
        "ms" = packages."ms@npm:2.1.2";
      };
      packagePeers = [
        "@types/supports-color"
        "supports-color"
      ];
    };
    "debug@virtual:be403fd6f7b6e95bd4aec31d1bf9c334857c71f759221be0219c12459d446557184251418833011b9a89f7d1cde9505518db3fa18f3c4021e9d387d9702dbff4#npm:4.3.4" = {
      name = "debug";
      reference = "virtual:be403fd6f7b6e95bd4aec31d1bf9c334857c71f759221be0219c12459d446557184251418833011b9a89f7d1cde9505518db3fa18f3c4021e9d387d9702dbff4#npm:4.3.4";
      canonicalPackage = packages."debug@npm:4.3.4";
      dependencies = {
        "ms" = packages."ms@npm:2.1.2";
      };
    };
    "esbuild-register@npm:3.4.1" = {
      name = "esbuild-register";
      reference = "npm:3.4.1";
      linkType = "HARD";
      outputName = "esbuild-register-3.4.1-2c0fbc0674";
      outputHash = "d215b8f5008f1d15ded08d7b7c883329808e38da9713c8f229360b987a177100f6ef29770aa899b4e2a6e2388a0b0d6f6113b1901b5324d755935ff98fcccb86";
      flatName = "esbuild-register";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^3.4.1";
      checksum = "10/d215b8f5008f1d15ded08d7b7c883329808e38da9713c8f229360b987a177100f6ef29770aa899b4e2a6e2388a0b0d6f6113b1901b5324d755935ff98fcccb86";
      dependencies = {
        "debug" = packages."debug@npm:4.3.4";
      };
      packagePeers = [
        "@types/esbuild"
        "esbuild"
      ];
    };
    "esbuild-register@virtual:55066ab27bd0662ac7a3999c80cf073281b6efcfe8250391af8ff681f2a227cf5b0b640e0c04304c19717e5107485d72c20d5b9bd2bab8ac0bfa8b0b73ea896b#npm:3.4.1" = {
      name = "esbuild-register";
      reference = "virtual:55066ab27bd0662ac7a3999c80cf073281b6efcfe8250391af8ff681f2a227cf5b0b640e0c04304c19717e5107485d72c20d5b9bd2bab8ac0bfa8b0b73ea896b#npm:3.4.1";
      canonicalPackage = packages."esbuild-register@npm:3.4.1";
      dependencies = {
        "esbuild" = packages."esbuild@npm:0.16.3";
        "debug" = packages."debug@virtual:be403fd6f7b6e95bd4aec31d1bf9c334857c71f759221be0219c12459d446557184251418833011b9a89f7d1cde9505518db3fa18f3c4021e9d387d9702dbff4#npm:4.3.4";
      };
    };
    "esbuild@npm:0.16.3" = {
      name = "esbuild";
      reference = "npm:0.16.3";
      linkType = "HARD";
      outputName = "esbuild-0.16.3-4dec320b34";
      outputHashByPlatform = {
        "x86_64-linux" = "sha512-8UxyetHT29Ml7DXfQTATezQXwR0YRZ7iRViVPi7o4UgAMiXBJyLd3GOhCaANl/LzzzqhFNTpsJNfp0ldV09l6A==";
      };
      shouldBeUnplugged = true;
      flatName = "esbuild";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.16.3";
      checksum = "10/bf2c6be0fc0f721f15eea0500cab626e7ce54cf28ac30422336538a6fcfb3d4ec3451360a624ad8dc96023de945bc114711021d4b71d12fc51f22cd7f3546781";
      bin = {
        "esbuild" = "bin/esbuild";
      };
      dependencies = {
        "@esbuild/android-arm64" = packages."@esbuild/android-arm64@npm:0.16.3";
        "@esbuild/android-arm" = packages."@esbuild/android-arm@npm:0.16.3";
        "@esbuild/android-x64" = packages."@esbuild/android-x64@npm:0.16.3";
        "@esbuild/darwin-arm64" = packages."@esbuild/darwin-arm64@npm:0.16.3";
        "@esbuild/darwin-x64" = packages."@esbuild/darwin-x64@npm:0.16.3";
        "@esbuild/freebsd-arm64" = packages."@esbuild/freebsd-arm64@npm:0.16.3";
        "@esbuild/freebsd-x64" = packages."@esbuild/freebsd-x64@npm:0.16.3";
        "@esbuild/linux-arm64" = packages."@esbuild/linux-arm64@npm:0.16.3";
        "@esbuild/linux-arm" = packages."@esbuild/linux-arm@npm:0.16.3";
        "@esbuild/linux-ia32" = packages."@esbuild/linux-ia32@npm:0.16.3";
        "@esbuild/linux-loong64" = packages."@esbuild/linux-loong64@npm:0.16.3";
        "@esbuild/linux-mips64el" = packages."@esbuild/linux-mips64el@npm:0.16.3";
        "@esbuild/linux-ppc64" = packages."@esbuild/linux-ppc64@npm:0.16.3";
        "@esbuild/linux-riscv64" = packages."@esbuild/linux-riscv64@npm:0.16.3";
        "@esbuild/linux-s390x" = packages."@esbuild/linux-s390x@npm:0.16.3";
        "@esbuild/linux-x64" = packages."@esbuild/linux-x64@npm:0.16.3";
        "@esbuild/netbsd-x64" = packages."@esbuild/netbsd-x64@npm:0.16.3";
        "@esbuild/openbsd-x64" = packages."@esbuild/openbsd-x64@npm:0.16.3";
        "@esbuild/sunos-x64" = packages."@esbuild/sunos-x64@npm:0.16.3";
        "@esbuild/win32-arm64" = packages."@esbuild/win32-arm64@npm:0.16.3";
        "@esbuild/win32-ia32" = packages."@esbuild/win32-ia32@npm:0.16.3";
        "@esbuild/win32-x64" = packages."@esbuild/win32-x64@npm:0.16.3";
      };
    };
    "ip-matching@npm:2.1.2" = {
      name = "ip-matching";
      reference = "npm:2.1.2";
      linkType = "HARD";
      outputName = "ip-matching-2.1.2-60bdd3d654";
      outputHash = "e9b32a6b603c97be449aabad0e44ff1426f4be13808b20b7c73e9e44bfa497049922eea9db7ae33ab5193c36b906df1b8dfab01985669ba644ffd1bef18e33a0";
      flatName = "ip-matching";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.1.2";
      checksum = "10/e9b32a6b603c97be449aabad0e44ff1426f4be13808b20b7c73e9e44bfa497049922eea9db7ae33ab5193c36b906df1b8dfab01985669ba644ffd1bef18e33a0";
    };
    "ms@npm:2.1.2" = {
      name = "ms";
      reference = "npm:2.1.2";
      linkType = "HARD";
      outputName = "ms-2.1.2-ec0c1512ff";
      outputHash = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f";
      flatName = "ms";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:2.1.2";
      checksum = "10/673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f";
    };
    "redux-saga@npm:1.2.1" = {
      name = "redux-saga";
      reference = "npm:1.2.1";
      linkType = "HARD";
      outputName = "redux-saga-1.2.1-4875573c97";
      outputHash = "ab957c91231d7080b56a5ed424352fac4e9f76afb2d597f394cb4bf6e2cb39be57b7a8a26c35124e37985bdbe561b53f933ef43b975ead1a1c2ec7055f5de889";
      flatName = "redux-saga";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.2.1";
      checksum = "10/ab957c91231d7080b56a5ed424352fac4e9f76afb2d597f394cb4bf6e2cb39be57b7a8a26c35124e37985bdbe561b53f933ef43b975ead1a1c2ec7055f5de889";
      dependencies = {
        "@redux-saga/core" = packages."@redux-saga/core@npm:1.2.1";
      };
    };
    "redux@npm:4.2.0" = {
      name = "redux";
      reference = "npm:4.2.0";
      linkType = "HARD";
      outputName = "redux-4.2.0-4688cc8d65";
      outputHash = "d3c586271732f0838f7439c1a914d01ca67b4e048a1568256194e324f8826e725938eadf63450953d553c13ec1b85fe5b13b6e7d34c375bba0bedd5a04389f94";
      flatName = "redux";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^4.0.4";
      checksum = "10/d3c586271732f0838f7439c1a914d01ca67b4e048a1568256194e324f8826e725938eadf63450953d553c13ec1b85fe5b13b6e7d34c375bba0bedd5a04389f94";
      dependencies = {
        "@babel/runtime" = packages."@babel/runtime@npm:7.20.6";
      };
    };
    "regenerator-runtime@npm:0.13.11" = {
      name = "regenerator-runtime";
      reference = "npm:0.13.11";
      linkType = "HARD";
      outputName = "regenerator-runtime-0.13.11-90bf536060";
      outputHash = "d493e9e118abef5b099c78170834f18540c4933cedf9bfabc32d3af94abfb59a7907bd7950259cbab0a929ebca7db77301e8024e5121e6482a82f78283dfd20c";
      flatName = "regenerator-runtime";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.13.11";
      checksum = "10/d493e9e118abef5b099c78170834f18540c4933cedf9bfabc32d3af94abfb59a7907bd7950259cbab0a929ebca7db77301e8024e5121e6482a82f78283dfd20c";
    };
    "stream-chain@npm:2.2.5" = {
      name = "stream-chain";
      reference = "npm:2.2.5";
      linkType = "HARD";
      outputName = "stream-chain-2.2.5-ad363478fb";
      outputHash = "f9c65fe21251106083ca753d8b36f5a35dc426f5cb12851d9a872b6eb69e30ea2c94d87887bfda8c820503e842183812922532fb2adab18d5878d31a4516b956";
      flatName = "stream-chain";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.2.5";
      checksum = "10/f9c65fe21251106083ca753d8b36f5a35dc426f5cb12851d9a872b6eb69e30ea2c94d87887bfda8c820503e842183812922532fb2adab18d5878d31a4516b956";
    };
    "stream-json@npm:1.7.5" = {
      name = "stream-json";
      reference = "npm:1.7.5";
      linkType = "HARD";
      outputName = "stream-json-1.7.5-47509e8de8";
      outputHash = "f54aea2f116ab54ec9e6baa30bf0cbff928a4ac131779522ef919a6d0a26834e3f9b07b454f0ba6d25701bacf029334fdc1078e7ee97a4e9c68b1bebfbd93275";
      flatName = "stream-json";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^1.7.5";
      checksum = "10/f54aea2f116ab54ec9e6baa30bf0cbff928a4ac131779522ef919a6d0a26834e3f9b07b454f0ba6d25701bacf029334fdc1078e7ee97a4e9c68b1bebfbd93275";
      dependencies = {
        "stream-chain" = packages."stream-chain@npm:2.2.5";
      };
    };
    "tailscale-prometheus-sd@workspace:." = {
      name = "tailscale-prometheus-sd";
      reference = "workspace:.";
      linkType = "SOFT";
      outputName = "tailscale-prometheus-sd-0.0.0-55066ab27b";
      src = ./.;
      shouldBeUnplugged = true;
      flatName = "tailscale-prometheus-sd";
      languageName = "unknown";
      scope = null;
      descriptorRange = "workspace:.";
      bin = {
        "tailscale-prometheus-sd" = "tailscale-prometheus-sd.js";
      };
      dependencies = {
        "@types/node" = packages."@types/node@npm:18.11.12";
        "ip-matching" = packages."ip-matching@npm:2.1.2";
        "redux-saga" = packages."redux-saga@npm:1.2.1";
        "stream-chain" = packages."stream-chain@npm:2.2.5";
        "stream-json" = packages."stream-json@npm:1.7.5";
      };
      devDependencies = {
        "esbuild" = packages."esbuild@npm:0.16.3";
        "esbuild-register" = packages."esbuild-register@virtual:55066ab27bd0662ac7a3999c80cf073281b6efcfe8250391af8ff681f2a227cf5b0b640e0c04304c19717e5107485d72c20d5b9bd2bab8ac0bfa8b0b73ea896b#npm:3.4.1";
        "typescript" = packages."typescript@patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=af41af";
      };
    };
    "typescript-compare@npm:0.0.2" = {
      name = "typescript-compare";
      reference = "npm:0.0.2";
      linkType = "HARD";
      outputName = "typescript-compare-0.0.2-86f99ed6e8";
      outputHash = "d6c43213e7689f8519438b6deceb9877cdc83b4f64677bbc07e6d88d8b63bee713035731678facfd3f81b019b93131a876a230194b4f8d31737bfc5af71594d2";
      flatName = "typescript-compare";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.0.2";
      checksum = "10/d6c43213e7689f8519438b6deceb9877cdc83b4f64677bbc07e6d88d8b63bee713035731678facfd3f81b019b93131a876a230194b4f8d31737bfc5af71594d2";
      dependencies = {
        "typescript-logic" = packages."typescript-logic@npm:0.0.0";
      };
    };
    "typescript-logic@npm:0.0.0" = {
      name = "typescript-logic";
      reference = "npm:0.0.0";
      linkType = "HARD";
      outputName = "typescript-logic-0.0.0-f343262bb5";
      outputHash = "84506bd58b7e15455b3233ded7f43f2ff8667500dca94f8e96e61aa16fa5a78bd9c45455f27c49f0e4aee7322c3e5a4b270e68bf8ba29fdf1571256fe2607152";
      flatName = "typescript-logic";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^0.0.0";
      checksum = "10/84506bd58b7e15455b3233ded7f43f2ff8667500dca94f8e96e61aa16fa5a78bd9c45455f27c49f0e4aee7322c3e5a4b270e68bf8ba29fdf1571256fe2607152";
    };
    "typescript-tuple@npm:2.2.1" = {
      name = "typescript-tuple";
      reference = "npm:2.2.1";
      linkType = "HARD";
      outputName = "typescript-tuple-2.2.1-b78fa3093a";
      outputHash = "6e03ff36696aa0b832465234f1ce5496717b50b22c8597f903894a1e7577ab0d0d86eeb84d509dc206f02aa21a75d196c0082d59325fde3ac9a22b6bc5ff3d14";
      flatName = "typescript-tuple";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:^2.2.1";
      checksum = "10/6e03ff36696aa0b832465234f1ce5496717b50b22c8597f903894a1e7577ab0d0d86eeb84d509dc206f02aa21a75d196c0082d59325fde3ac9a22b6bc5ff3d14";
      dependencies = {
        "typescript-compare" = packages."typescript-compare@npm:0.0.2";
      };
    };
    "typescript@npm:4.9.1-beta" = {
      name = "typescript";
      reference = "npm:4.9.1-beta";
      linkType = "HARD";
      outputName = "typescript-4.9.1-beta-7ff573487c";
      outputHash = "8060879069038a573b4e853d070611c8c8d2d609f945d09481be36d9769652a58efd7190c61f9e0af980d6b4241190742505d5c0904f6b79e16fc8a6cde864b9";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "npm:4.9.1-beta";
      checksum = "10/8060879069038a573b4e853d070611c8c8d2d609f945d09481be36d9769652a58efd7190c61f9e0af980d6b4241190742505d5c0904f6b79e16fc8a6cde864b9";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
    "typescript@patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=af41af" = {
      name = "typescript";
      reference = "patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>::version=4.9.1-beta&hash=af41af";
      linkType = "HARD";
      outputName = "typescript-4.9.1-beta-a6fd484f31";
      outputHash = "415935d6fc65ac5e4e7e90c0597941752ac9fde3447684b9eeef3555563d61e1c63ed35784262a1698edf3a4e11a140c1e02d66791b09f4d122c964c5be767b5";
      flatName = "typescript";
      languageName = "node";
      scope = null;
      descriptorRange = "patch:typescript@npm%3A4.9.1-beta#optional!builtin<compat/typescript>";
      checksum = "10/415935d6fc65ac5e4e7e90c0597941752ac9fde3447684b9eeef3555563d61e1c63ed35784262a1698edf3a4e11a140c1e02d66791b09f4d122c964c5be767b5";
      bin = {
        "tsc" = "bin/tsc";
        "tsserver" = "bin/tsserver";
      };
    };
  };
in
{ inherit packages; inherit settings; }
